name: tests-taxonomy

on:
  pull_request:
    paths:
      - 'taxonomy/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd taxonomy && npm install && npm run test:ci
